### ISSUE TITLE
Prop Handling while passing down JSON sections

### ISSUE THREAD

**Issue by rarchitgupta** [rarchitgupta/portfolio_v2#1]
The JSON file is being parsed and passed down to sections of the page. Not properly typed and the variables are not named or handled well. Example: The props in Experience.tsx. Need to type the props well for the complete TypeScript experience

**Comment by Albx68** [comment]
Please check #2 :D

**Comment by rarchitgupta** [comment]
Thanks for the PR, closing this down :)
